mybatis:
  type-aliases-package: com.hanhf.demo.pojo
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8

server:
  port: 8081