mybatis:
  type-aliases-package: com.hanhf.demo.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081

spring:
  datasource:
    username: root
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#showSql
logging:
  level:
    com.example.demo.mapper: debug

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql